### PR TITLE
Tests for output shape and gradients visualization + bugfix

### PR DESCRIPTION
**Pull request by robintibor**

### CODE REVIEW

**Comment by robintibor** [comment]
and even found a bug! @agramfort must be so happy :)
Before, amplitude gradients were accidentally summed over filters, so gradient for filter 3 would be sum of grads filter 0,1,2,3 instead of being just gradient of filter 3 as intended.

**Comment by agramfort** [comment]
I am happy but I would be even happier if you could update changelog to document the bug fix :)

**Comment by robintibor** [comment]
Now I am sure you are so happy you want to invite me me for a Pizza Pesto from https://www.la-guichetta.fr/notre-carte/pizzas-au-feu-de-bois/ , correct? :)

**Comment by agramfort** [comment]
I won't pay the full pizza yet :) 

what I have in mind is something like: https://mne.tools/stable/whats_new.html
or https://scikit-learn.org/stable/whats_new/v0.23.html

so it appears on the website so contributors get public credit for their efforts!

**Comment by robintibor** [comment]
hmhm ok for now I will merge this so there is at least anything. then go further in separate pr

**Pull request merged**
