### PR TITLE
[WIP] Scikit-learn hyperparameter tuning example

### PR DESCRIPTION
**Pull request by gemeinl**
added a scikit-learn hyperparameter tuning example

### CODE REVIEW

**Comment by bruAristimunha** [comment]
Hi @gemeinl

When I tried to reproduce this script from your branch, I got an error: 

`TypeError: Cannot convert this data type to a NumPy array.`

Then, using a compression list, I transformed the SliceDataset into a NumPy array and got this second error:

`ValueError: You are using a non-skorch dataset that returns 1 value. Remember that for skorch, Dataset.__getitem__ must return exactly 2 values, X and y (more info:[ https://skorch.readthedocs.io/en/stable/user/dataset.html](https://skorch.readthedocs.io/en/stable/user/dataset.html)).`

I tried to mix the slicedataset (X values) and the numpy array for the classes, following an example on the page of skorch, but I got the same error. I also tried to create the dataset inheriting the Dataset from skorch, and it also didn't work.

I didn't know which change I applied to the dataset during my test, but it strangely worked well twice. Unfortunately, I can not reproduce it later )=

The code is available in this colab:  https://colab.research.google.com/drive/14dxA1nlry3urHjkHO-A7Twj_xtsvl0xU?usp=sharing
Can you help me?

**Comment by gemeinl** [comment]
Hi, I don't really know what is going on yet, I would to have a closer look at this.
For now, creating an numpy ndarray for the targets should get the code running:
```clf.fit(train_X, np.array([y for y in train_y]))```

**Comment by bruAristimunha** [comment]
Hello Lukas @gemeinl,

I am wondering if I could perhaps assist in this PR.

**Comment by gemeinl** [comment]
Hi @bruAristimunha ,
yeah, sure! Feel free to take over :)

**Comment by bruAristimunha** [comment]
Hi @gemeinl,

I created a PR in your folk, link https://github.com/gemeinl/braindecode-1/pull/2. You need to accept to get to braindecode.

**Comment by bruAristimunha** [comment]
Hey @gemeinl,

Many thanks for the permission. If you're happy with the proposed changes, can you merge the pull request?

**Review by agramfort — APPROVED** [review]
LGTM !

https://output.circle-artifacts.com/output/job/da0827cd-420a-4a7a-ab65-dddf61a9aa7d/artifacts/0/dev/auto_examples/plot_hyperparameter_tuning_with_scikit-learn.html

thx @bruAristimunha

**Comment by bruAristimunha** [comment]
@agramfort, could you merge?

**Comment by agramfort** [comment]
Thx @bruAristimunha 🙏

**Pull request merged**
