### PR TITLE
Fix CI Problems PyTorch CPU

### PR DESCRIPTION
**Pull request by robintibor**
So we seem to have issues related to https://github.com/pytorch/pytorch/issues/49462 that have caused Travis CI to fail.

E.g. 
```python
a = torch.ones(16, 1, 100, 2)
conv = Conv2d(1, 40, kernel_size=(20, 1), stride=(1, 1))
conv(a)
```
even causes crashes already on CPU PyTorch, unrelated to braindecode.

Installing via pip seems to resolve this for now, probably have to wait for next PyTorch release for proper fix. Segmentation Fault still happens locally for unknown reasons on CPU, but at least one can see that tests pass.

Also need to add wfdb and pyunpack to installations for CircleCI and Travis.

### CODE REVIEW

**Comment by robintibor** [comment]
SegFaults don't know if we can do anything about them, see:
https://github.com/pytorch/pytorch/issues/50858
https://github.com/pytorch/pytorch/issues/47161
https://github.com/pytorch/pytorch/issues/50014
https://github.com/pytorch/pytorch/issues/42125

So maybe also have to wait for next PyTorch release.

**Comment by agramfort** [comment]
Thx @robintibor 

can you tell me why we need the two new dependencies ?

**Comment by robintibor** [comment]
So, for pyunpack, moabb seems to use it: https://app.circleci.com/pipelines/github/braindecode/braindecode/531/workflows/02b19991-8bb0-48bd-9c13-9428003b89b5/jobs/631 

```python
  File "/home/circleci/.local/lib/python3.7/site-packages/moabb/datasets/__init__.py", line 23, in <module>
    from .ssvep_wang import Wang2016
  File "/home/circleci/.local/lib/python3.7/site-packages/moabb/datasets/ssvep_wang.py", line 15, in <module>
    from pyunpack import Archive
ModuleNotFoundError: No module named 'pyunpack'
```
wfdb I think something similar

**Comment by agramfort** [comment]
I would suggest to fix the issue upstream:

https://github.com/NeuroTechX/moabb/blob/master/setup.py#L11

**Comment by robintibor** [comment]
Or should we maybe change our installation of Moabb? This is our steps in braindecode.org main docu, these ones work since they also install requirements from requirements.txt from moabb:
```
pip install download
python -c "from download import download; download('https://raw.githubusercontent.com/NeuroTechX/moabb/master/requirements.txt', 'requirements.txt', replace=True)"
pip install -r requirements.txt
rm requirements.txt
pip install -U https://github.com/NeuroTechX/moabb/archive/master.zip
```

Instead in circleci, we do like this:
https://github.com/braindecode/braindecode/blob/53722c8b22ed89c7b8e168f1aa5da946a23ee203/.circleci/config.yml#L57-L61

In Travis:

https://github.com/braindecode/braindecode/blob/53722c8b22ed89c7b8e168f1aa5da946a23ee203/.travis.yml#L22-L24
https://github.com/braindecode/braindecode/blob/53722c8b22ed89c7b8e168f1aa5da946a23ee203/environment.yml#L17-L22

**Comment by agramfort** [comment]
we should have one environment.yml or requirements.txt file we use both for
travis and circle CI
and avoid the line by line pip install we do here.
we should also consider switch to GH actions for faster CIs

>

**Comment by robintibor** [comment]
@ErikBjare @sylvchev seems maybe there is some problem with scikit learn version required by moabb in one of our examples?

Is there a reason for the specific upper limits on the versions in the setup.py install_requires on pypi, e.g. scikit-learn/scipy?

I think this error only happened once I switched to pip install of moabb:
https://app.circleci.com/pipelines/github/braindecode/braindecode/547/workflows/4944f620-8da4-405a-ab5c-fdd182b0145f/jobs/650
```
WARNING: /home/circleci/project/examples/plot_relative_positioning.py failed to execute correctly: Traceback (most recent call last):
  File "/home/circleci/project/examples/plot_relative_positioning.py", line 482, in <module>
    clf_pipe.fit(*data['train'])
  File "/home/circleci/.local/lib/python3.7/site-packages/sklearn/pipeline.py", line 335, in fit
    self._final_estimator.fit(Xt, y, **fit_params_last_step)
  File "/home/circleci/.local/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py", line 1417, in fit
    for class_, warm_start_coef_ in zip(classes_, warm_start_coef))
  File "/home/circleci/.local/lib/python3.7/site-packages/joblib/parallel.py", line 1041, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/circleci/.local/lib/python3.7/site-packages/joblib/parallel.py", line 859, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/circleci/.local/lib/python3.7/site-packages/joblib/parallel.py", line 777, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/circleci/.local/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/home/circleci/.local/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/home/circleci/.local/lib/python3.7/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/home/circleci/.local/lib/python3.7/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/circleci/.local/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py", line 764, in _logistic_regression_path
    extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
  File "/home/circleci/.local/lib/python3.7/site-packages/sklearn/utils/optimize.py", line 243, in _check_optimize_result
    ).format(solver, result.status, result.message.decode("latin1"))
AttributeError: 'str' object has no attribute 'decode'

```

**Comment by ErikBjare** [comment]
@robintibor The sklearn limitation is due to an issue in pyRiemann: https://github.com/alexandrebarachant/pyRiemann/pull/93

The fix was recently merged, but there hasn't been a new release yet, so we can't bump it and remove the sklearn constraint from moabb (and @alexandrebarachant is a bit slow to respond on GitHub). We might work around this by installing pyriemann from git if Alexandre takes his time with a new release.

**Comment by robintibor** [comment]
I see. well would be great if it can be fixed somehow, until then we will have to reinstall scikitlearn newer version after moabb.

**Comment by robintibor** [comment]
@agramfort So with 2 hour no-output timelimit there was a successful build on CircleCI: 
https://app.circleci.com/pipelines/github/braindecode/braindecode/599/workflows/7838a72f-911b-4557-9a4e-c9e9e60b2a42/jobs/705

But took 3 hours 30 minutes... Saving Cache seemed successful.

I restarted the workflow, and also restoring cache was successful, but let's see how long it will run now:

https://app.circleci.com/pipelines/github/braindecode/braindecode/599/workflows/24c7c9ab-baf1-4fb7-a1cc-68807b61cfc2/jobs/707

**Comment by robintibor** [comment]
I also don't know what to think about this:
https://app.circleci.com/settings/plan/github/braindecode/overview
image
image

**Comment by robintibor** [comment]
Seems rebuild now succeeded in 31 minutes, with those doc generation times https://app.circleci.com/pipelines/github/braindecode/braindecode/599/workflows/24c7c9ab-baf1-4fb7-a1cc-68807b61cfc2/jobs/707

```

computation time summary:
    - ../examples/plot_relative_positioning.py:       633.69 sec    559.0 MB
    - ../examples/plot_sleep_staging.py:              457.81 sec    176.6 MB
    - ../examples/plot_bcic_iv_2a_moabb_cropped.py:   437.24 sec   1017.6 MB
    - ../examples/plot_bcic_iv_2a_moabb_trial.py:     184.27 sec   1131.7 MB
    - ../examples/plot_regression.py:                  25.79 sec    187.8 MB
    - ../examples/plot_split_dataset.py:               13.46 sec    406.2 MB
    - ../examples/plot_dataset_example.py:              7.74 sec    385.8 MB
    - ../examples/plot_mne_dataset_example.py:          0.89 sec     68.9 MB
    - ../examples/plot_custom_dataset_example.py:       0.69 sec    116.8 MB
    - ../examples/benchmark_lazy_eager_loading.py:      0.00 sec      0.0 MB
 ```

Still seems very slow to me for the limited number of examples we are running and compared to Github Actions as well

**Comment by robintibor** [comment]
But for me it's fine, I could remove travis, add github actions badge and then we continue like this for now, what do you think @agramfort ?

**Comment by ErikBjare** [comment]
@robintibor I've worked on a similar thing (docs building and dataset caching) in moabb: https://github.com/NeuroTechX/moabb/pull/174

Why use Circle CI in the first place? I see you had it working for GitHub Actions at one point: https://github.com/braindecode/braindecode/actions/runs/742544554/workflow

**Comment by robintibor** [comment]
agramfort very much likes to see html docs directly via click as CircleCI offers 
https://github.com/braindecode/braindecode/pull/199#issuecomment-818515598

**Comment by ErikBjare** [comment]
I see, you could get the equivalent result by deploying the artifacts to S3 or GitHub Pages though (as done in my moabb PR).

**Pull request merged**
