### PR TITLE
[WIP][DOC] add structure to example gallery

### PR DESCRIPTION
**Pull request by dengemann**
As discussed earlier, this adds sections to the gallery. Some fine-tuning may be needed. Let's see if build works here. cc @bruAristimunha @robintibor

### CODE REVIEW

**Comment by bruAristimunha** [comment]
closes #455

**Comment by bruAristimunha** [comment]
Hi @dengemann!

Can I work in the PR?

**Comment by dengemann** [comment]
Sure go ahead!

**Comment by bruAristimunha** [comment]
Hi @dengemann, @robintibor and @agramfort,

I think I finished the re-organization of the documentation. During the process, I re-created the installation pages. Fixed something related to skorch and the examples. I fixed something that was disabled or not working in the documentation, e.g., institutions on the front page and the source button. And several small details. Can you please check? I think it would be nice to have the new documentation integrated ASAP to focus on the other tasks for the code sprint. 🙏🏽 

I thank you in advance for your time reviewing.

**Comment by bruAristimunha** [comment]
Here is the link for the artifact: https://github.com/braindecode/braindecode/suites/15663207492/artifacts/894131735 . @dengemann, @agramfort and @martinwimpff

**Pull request merged**
