### PR TITLE
FIX class documentation for inherited methods

### PR DESCRIPTION
**Pull request by tomMoral**
This PR intends to avoid documenting inherited methods and changes the way the classes are described (see the template).

Questions are:

- do we want to modify this template, in particular the way attributes are documented.
- Are we sure we do not want to document any inherited methods? (it seems doable to only filter out the methods from `torch.nn.Module` for instance if necessary).

### CODE REVIEW

**Comment by agramfort** [comment]
looks great https://1184-232335424-gh.circle-artifacts.com/0/dev/index.html !

**Comment by agramfort** [comment]
@robintibor can you merge this?

**Comment by tomMoral** [comment]
Note that this removes the list of methods at the beginning:

image
image


Also, it  seems that the attributes are documented in the docstring so should I remove them?

**Comment by tomMoral** [comment]
For the before/after on he models:

- before: https://braindecode.org/generated/braindecode.models.EEGNetv1.html
- after: https://1184-232335424-gh.circle-artifacts.com/0/dev/generated/braindecode.models.EEGNetv1.html#braindecode.models.EEGNetv1

**Comment by agramfort** [comment]
I love it as it is !

>

**Comment by robintibor** [comment]
Please indicate if ready to merge @tomMoral

**Comment by agramfort** [comment]
beautiful 

https://1212-232335424-gh.circle-artifacts.com/0/dev/generated/braindecode.models.EEGNetv4.html

thx @tomMoral !

**Pull request merged**
