### PR TITLE
Replacing the real dataset

### PR DESCRIPTION
**Pull request by bruAristimunha**

### CODE REVIEW

**Comment by bruAristimunha** [comment]
Not super good, same average speed @robintibor, but we can work more in the future. My opinion, merge this PR and leave the issue open.

**Comment by robintibor** [comment]
Hm, would argue for removing this from what's new? like some internal test stuff not really useful to know for any user?

**Comment by bruAristimunha** [comment]
indeed @robintibor,  I ended up realizing that there was a small error in the whats new file. I fixed the file.

**Comment by robintibor** [comment]
great, merged

**Pull request merged**
