### PR TITLE
Allow passing only model name

### PR DESCRIPTION
**Pull request by PierreGtch**
Allow passing only the name of a braindecode model  to `_EEGNNeuralNetwork`.
This is easy to implement and facilitates the usage of config files.

#457

### CODE REVIEW

**Review by bruAristimunha — APPROVED** [review]

**Comment by bruAristimunha** [comment]
Hey, 

Can you create one test and update the whats_new file @PierreGtch?

**Comment by PierreGtch** [comment]
@bruAristimunha yes I'm just waiting to merge #517 to put the tests in `test_eegneuralnet.py`

**Review by sliwy — APPROVED** [review]

**Comment by PierreGtch** [comment]
@bruAristimunha Ready to merge

**Comment by bruAristimunha** [comment]
Thank you @PierreGtch and @sliwy ;)

**Pull request merged**
