### PR TITLE
Added pillow to docs requirements andchange mne to install from pypi

### PR DESCRIPTION
**Pull request by sliwy**
I think it should solve failing CI as it shows lack of Pillow package

### CODE REVIEW

**Comment by sliwy** [comment]
One more thing I had to change to make it green was the version of mne. As I see mne version on pypi was bumped and now 0.20.0 is the default version, so we do not need to install mne from github. There were some changes in mne on the newest version that resulted in moabb crash.

**Comment by agramfort** [comment]
thx @sliwy

**Comment by robintibor** [comment]
> One more thing I had to change to make it green was the version of mne. As I see mne version on pypi was bumped and now 0.20.0 is the default version, so we do not need to install mne from github. There were some changes in mne on the newest version that resulted in moabb crash.

@sylvchev can you help with this?

**Comment by agramfort** [comment]
It's an issue that mne killed deprecated features from 0.20 already in master.

moabb should now be adjusted to avoid using deprecated features from 0.20

mne master is now 0.21.dev

braindecode should stick to 0.20 stable for now

**Comment by sylvchev** [comment]
I'll check this on MOABB and keep you posted.

**Pull request merged**
