### PR TITLE
change raise error to warn user when target_name is not in description

### PR DESCRIPTION
**Pull request by gemeinl**

### CODE REVIEW

**Comment by gemeinl** [comment]
I have no clue why the tests fail. I did not make any changes that affect them.

**Comment by agramfort** [comment]
@gemeinl I suspect a pytorch/numpy/skorch version update

**Comment by gemeinl** [comment]
You are right, it is pytorch 1.8.0 -> 1.9.0.

**Comment by robintibor** [comment]
oki great now tests running, merged

**Pull request merged**
