### PR TITLE
Update base.py

### PR DESCRIPTION
**Pull request by MohammadJavadD**
Add `list` to acceptable types for `target_names`.  It solves this issue: #370

### CODE REVIEW

**Review by agramfort — COMMENTED** [review]
can you update an existing test to avoid a future regression and to make sure these new lines are covered by some test?

**Comment by robintibor** [comment]
Thanks @MohammadJavadD  for the PR, have tried to address comments and clean up a bit. @gemeinl would be nice if you can check if this makes sense for you or you anticipate any problems?

**Review by agramfort — APPROVED** [review]
🙏 can you just add an entry in what's new to document the bug fix?

**Review by agramfort — APPROVED** [review]

**Comment by gemeinl** [comment]
Thanks @MohammadJavadD @robintibor 
Please also add `list` to the accepted types for `target_name` in `load_concat_dataset` (https://github.com/braindecode/braindecode/blob/ad0ab1a1f823da3d0a88eda3928ccd96601d1dba/braindecode/datautil/serialization.py#L139-L141)

It appears the usage of `target_name` in `load_concat_dataset` is not tested at all. It should be tested of course but can be a separate PR.

**Pull request merged**
