### PR TITLE
[WIP] TUH updates

### PR DESCRIPTION
**Pull request by gemeinl**
-improved selection of recordings to be loaded
-added verbose argument to suppress mne logging

### CODE REVIEW

**Comment by gemeinl** [comment]
@MFattouh Do these changes work for your use case?

**Comment by robintibor** [comment]
Is this still relevant @MFattouh ?

**Comment by MFattouh** [comment]
@robintibor yes of course. On top of potential performance improvements, I think this code refactor makes it easier to extend the behavior of TUH constructor.

**Comment by robintibor** [comment]
Closing this for now as it is unfinished and doesn't have somebody right now motivated to work on it, can still be reopened if somebody feels interested.

**Pull request closed without merging**
