### PR TITLE
CI : attempt to fix circle-ci cache

### PR DESCRIPTION
**Pull request by agramfort**

### CODE REVIEW

**Comment by robintibor** [comment]
You might also need the change in https://github.com/braindecode/braindecode/pull/190/files 
https://github.com/braindecode/braindecode/pull/190/files#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47R60

But maybe not necessary, maybe if moabb not installed via pip, maybe it doesn't downgrade scikit learn

**Comment by agramfort** [comment]
Shall I push directly on your branch?

>

**Comment by robintibor** [comment]
Also possible, feel free to do it. of course always annoying waiting times on CircleCI atm to see if anything really works :)

**Comment by agramfort** [comment]
I have long meetings in parallel....

>

**Pull request closed without merging**
