### PR TITLE
First commit for python tutorial

### PR DESCRIPTION
**Pull request by remidbs**
Added a pure torch version of the [train/test tutorial](https://braindecode.org/dev/auto_examples/model_building/plot_how_train_test_and_tune.html#option-2-train-val-test-split).

Most of the data loading and preprocessing is similar, main differences are the two last paragraph showcasing a torch training loop and an equivalent pytorch lightning loop.

### CODE REVIEW

**Comment by remidbs** [comment]
cc @bruAristimunha 

Feel free to build on this and change as many things as you think is relevant!
I'll also need your stamp for triggering the workflows

**Comment by bruAristimunha** [comment]
Triggered ;)

**Review by bruAristimunha — APPROVED** [review]

**Comment by bruAristimunha** [comment]
Can you check the render html @remidbs?
https://output.circle-artifacts.com/output/job/f6521e54-ecf8-46e0-9da8-cc2cc3652b04/artifacts/0/dev/auto_examples/model_building/plot_train_in_pure_pytorch_and_pytorch_lightning.html#sphx-glr-auto-examples-model-building-plot-train-in-pure-pytorch-and-pytorch-lightning-py

**Comment by remidbs** [comment]
Thanks for these nice edits!

Just did tiny edits, otherwise LGTM :)

I also added you as an author now that you built on this.

I'll need your workflow approval to ensure I didn't break any CI job.

**Comment by bruAristimunha** [comment]
Thank you, so much @remidbs! 

Once the CI has been updated, you can check out your tutorial on the braindecode dev page.

Congratulations on your first PR on braindecode ;) Feel invited to always contribute to braindecode!

Please let me know if there is any way to do more cross-over between what you are working on and the braindecode (maybe another biosignal). I'm super interested in having you on board!

**Comment by remidbs** [comment]
Thank you! pleasure to collaborate! looking forward to the next time :)

**Pull request merged**
