### PR TITLE
Adding poetry and changing the CI

### PR DESCRIPTION
**Pull request by bruAristimunha**

### CODE REVIEW

**Comment by agramfort** [comment]
@bruAristimunha pinning versions with == is a bad idea. It makes dev environnements impossible to update and most of us don't use a dedicated env for braindecode. I would suggest to use >= for versions.

**Comment by robintibor** [comment]
tend to agree with @agramfort

**Comment by bruAristimunha** [comment]
Closed @agramfort and @robintibor.

**Comment by agramfort** [comment]
I don't say we should close. You can still use poetry and not a setup
file but don't pin version numbers with == or <= as much as possible.
And I don't think lock files are necessary for us here.

**Comment by bruAristimunha** [comment]
I will start again!

**Pull request closed without merging**
