### PR TITLE
[WIP] Remove "trial_" prefix, issue 246

### PR DESCRIPTION
**Pull request by dcwil**
Fix for [246](https://github.com/braindecode/braindecode/issues/246):

"trial_" prefix removed from "trial_start_offset_samples" & "trial_stop_offset_samples" . Effects create_windows_from_events and create_from_mne_raw

changes by @Ann-KathrinKiessner, @vytjan, @HenrikBons & I

### CODE REVIEW

**Comment by robintibor** [comment]
Due to other PRs being merged, you probably have to rebase this from master, see end of the Contributing guide https://github.com/braindecode/braindecode/blob/765cd046a63f051a96a9019a5322473b4a501129/CONTRIBUTING.md

**Comment by agramfort** [comment]
you need to fix conflicts @dcwil

**Comment by robintibor** [comment]
@hubertjb @sliwy how do you feel about this change do we want it?
Change is renaming
`trial_start_offset_samples` and `trial_stop_offset_samples`
to 
`start_offset_samples` and `stop_offset_samples`
in `create_windows_from_events` to make it same name as in `create_from_mne_raw`

I mean variables do not mean same things but are similar, do we want them to have same name there?

**Comment by sliwy** [comment]
It's good to have similar API in both functions. However we should clarify all the doubts in the docstring. 
If we can crop signal with Preprocessors, let's do that in all tutorials and then remove those parameters from `create_fixed_length_windows`, so we have no confusion there.

**Comment by robintibor** [comment]
so @dcwil can you remove start_offset_samples and stop_offset_samples from create_fixed_length_windows ? also from _create_fixed_length_windows of course, just remove entire usage, so as if they were set to 0. in one test it is set to 100, but I think test should still just run fine when the argument is removed.

**Comment by gemeinl** [comment]
Closed in favor of https://github.com/braindecode/braindecode/issues/269. Will be done in separate PR.

**Pull request closed without merging**
