### PR TITLE
[WIP] Adding docstrings for models

### PR DESCRIPTION
**Pull request by dcwil**

### CODE REVIEW

**Comment by agramfort** [comment]
@dcwil are you planning to make progress on this quickly?

**Comment by dcwil** [comment]
@agramfort I have a couple of other projects I need to do some work on currently, so won't be able to do anything for the next couple of days but can put in a couple of evenings in the next week or two. 

I presume you would like to see a full docstring for every model available?

**Comment by agramfort** [comment]
yes it should be added for all models

anyone else can help?

>

**Comment by robintibor** [comment]
Maybe one from previous team @HenrikBons @Ann-KathrinKiessner @vytjan ?

**Comment by vytjan** [comment]
> Maybe one from previous team @HenrikBons @Ann-KathrinKiessner @vytjan ?

I can help with adding docstrings to the models. 
Although busy until Thursday, I will take a look at those by the end of this week, if that's fine with you @robintibor, @agramfort ?

**Comment by agramfort** [comment]
Thursday is fine. I would just like to keep the ball rolling

>

**Comment by robintibor** [comment]
Some Notes I made please recheck that true.
Unused parameters:
`third_kernel_size` in EEGNet
`double_time_convs` in Deep4

If true, these can be just removed

**Comment by robintibor** [comment]
Did you have a chance to take a look @vytjan ?

**Comment by vytjan** [comment]
@robintibor my apologies, it's in progress, but I got delayed due to side effects after my second covid vaccine shot. I'll push it tomorrow.

**Comment by robintibor** [comment]
So are you planning to do more @vytjan or should somebody else have a try for further ones?

**Comment by vytjan** [comment]
> So are you planning to do more @vytjan or should somebody else have a try for further ones?

Yes @robintibor I will do more of these in the upcoming days, thank you for reminding me about this.

**Comment by robintibor** [comment]
Merging this since no further activity.

**Pull request merged**
